<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE traveldocument [
        <!ELEMENT traveldocument (passenger|train)*>
        <!ELEMENT passenger (name|surname|dateofbirth|pasport)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT surname (#PCDATA)>
        <!ELEMENT dateofbirth (#PCDATA)>
        <!ELEMENT pasport (number|citizenship)*>
        <!ELEMENT number (#PCDATA)>
        <!ELEMENT citizenship (#PCDATA)>
        <!ELEMENT train (traintype|trainnumber|placenumber)*>
        <!ELEMENT traintype (#PCDATA)>
        <!ELEMENT trainnumber (#PCDATA)>
        <!ELEMENT placenumber (#PCDATA)>
        ]>
<traveldocument>
    <passenger>
        <name>Alexandr</name>
        <surname>Ivanov</surname>
        <dateofbirth>10.10.1988</dateofbirth>
        <pasport>
            <number>003280924</number>
            <citizenship>Kazakhstan</citizenship>
        </pasport>
    </passenger>
    <train>
        <traintype>high-speed</traintype>
        <trainnumber>V301</trainnumber>
        <placenumber>21</placenumber>

    </train>
</traveldocument>